[build]
builder = "nixpacks"

[deploy]
startCommand = "python -m streamlit run app.py --server.port $PORT --server.address 0.0.0.0"
restartPolicyType = "ON_FAILURE"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyMaxRetries = 5

[deploy.envs]
PORT = "8501"
STREAMLIT_SERVER_PORT = "8501"
STREAMLIT_SERVER_ADDRESS = "0.0.0.0"
STREAMLIT_SERVER_HEADLESS = "true"
STREAMLIT_SERVER_ENABLECORS = "true"
PYTHONUNBUFFERED = "1"
